<?php

namespace App\Models;

use App\Observers\MainCategoryObserver;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MainCategory extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        MainCategory::observe(MainCategoryObserver::class);
    }

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }

    public function getStatus()
    {
        return $this->status == '1' ? 'مفعل' : 'غير مفعل';
    }

    public function scopeSelection($query)
    {
        return $query->select('id', 'translation_lang', 'name', 'slug', 'image', 'status', 'translation_of');
    }



    public function getImageAttribute($val)
    {
        return $val !== null ? asset('assets/images/' . $val) : "";
    }

    public function categories()
    {
        return $this->hasMany(self::class, 'translation_of');
    }

    public function vendors()
    {
        return $this->hasMany(Vendor::class, 'category_id');
    }
}
